apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  APP_ENV: development
  LOG_LEVEL: debug
  SESSION_SECURE_COOKIE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-config
data:
  APP_ENV: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
